### PR TITLE
P3 versions of the components

### PR DESCRIPTION
**Pull request by yuriy-fix**
Fixes https://github.com/vaadin/components-team-tasks/issues/336

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/base-starter-vue/1)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[package.json, line 16 at r1](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1#-L9LDjWL4y-Zb4AhyTvk:-L9LDjWMAT6rfbagqLoi:b-b1g194) ([raw file](https://github.com/vaadin/base-starter-vue/blob/4f9987f67274fcd62064a65140e4efcf65b252e3/package.json#L16)):*
> ```JSON
>     "@polymer/polymer": "^3.0.0-pre.12",
>     "@vaadin/vaadin-button": "^2.0.0-pre.1",
>     "@vaadin/vaadin-text-field": "^2.0.0-pre.1"
> ```

Missing `@webcomponentsjs/webcomponentsjs`

---

*[src/main.js, line 4 at r1](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1#-L9LEB5w6W-TbmVLeFsT:-L9LEB5w6W-TbmVLeFsU:b-lmm2py) ([raw file](https://github.com/vaadin/base-starter-vue/blob/4f9987f67274fcd62064a65140e4efcf65b252e3/src/main.js#L4)):*
> ```JavaScript
> 
> import '@webcomponents/webcomponentsjs/webcomponents-loader.js';
> import '@vaadin/vaadin-button/vaadin-button.js';
> ```

BTW maybe it’s be more appropriate to import Vaadin components in the `App.vue` instead somehow, where they are actually used.

It’s fine to have the polyfill here though.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1#-L9LEjan6tGIiPxuuIQ6:-L9LEjan6tGIiPxuuIQ7:bug33zs) (no related file):*
BTW there is `document.getElementById` in the `App.vue`. Now I’m not an expect in Vue, but logically accessing document from an app view is a scope violation to me, that should not be encouraged. 

Looks like we have to replace that with a ref again: https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1#-L9LEjan6tGIiPxuuIQ6:-L9Lq2Po9RGowOiy9vF5:b-t4con0) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW there is `document.getElementById` in the `App.vue`. Now I’m not an expect in Vue, but logically accessing document from an app view is a scope violation to me, that should not be encouraged. 

Looks like we have to replace that with a ref again: https://vuejs.org/v2/guide/components-edge-cases.html#Accessing-Child-Component-Instances-amp-Child-Elements
</blockquote></details>

Consider using `v-model` instead of refs. That would require us to declare another property and bind the text-field value to it. This is how Vue is usually used to work with forms: https://vuejs.org/v2/guide/forms.html#Basic-Usage

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1)*

**Comment by yuriy-fix** [comment]
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1#-L9LEjan6tGIiPxuuIQ6:-L9Ow7XL-_iXXvZWP8J6:b-ki3nbq) (no related file):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Consider using `v-model` instead of refs. That would require us to declare another property and bind the text-field value to it. This is how Vue is usually used to work with forms: https://vuejs.org/v2/guide/forms.html#Basic-Usage
</blockquote></details>

I have changed to work with ref. Unfortunately it seems that `vaadin-text-field` doesn't support v-model (`:input`; `@input`). 
Something to consider for improvement in our elements.

---

*[package.json, line 16 at r1](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1#-L9LDjWL4y-Zb4AhyTvk:-L9Ow4dA2NMBHKGtK_ER:bt2vr1b) ([raw file](https://github.com/vaadin/base-starter-vue/blob/4f9987f67274fcd62064a65140e4efcf65b252e3/package.json#L16)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Missing `@webcomponentsjs/webcomponentsjs`
</blockquote></details>

Fixed.

---

*[src/main.js, line 4 at r1](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1#-L9LEB5w6W-TbmVLeFsT:-L9Ow6_-951ixEtEUTP2:b-a2ujfl) ([raw file](https://github.com/vaadin/base-starter-vue/blob/4f9987f67274fcd62064a65140e4efcf65b252e3/src/main.js#L4)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW maybe it’s be more appropriate to import Vaadin components in the `App.vue` instead somehow, where they are actually used.

It’s fine to have the polyfill here though.
</blockquote></details>

Changed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1)*

**Comment by platosha** [comment]
:lgtm: : 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1#-L9LEjan6tGIiPxuuIQ6:-L9PGeBh7riP2J4yjbxr:b-4zx56j) (no related file):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

I have changed to work with ref. Unfortunately it seems that `vaadin-text-field` doesn't support v-model (`:input`; `@input`). 
Something to consider for improvement in our elements.
</blockquote></details>

Fine by me, that’s the approach we use in the other starters BTW, so good to match.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1#-:-L9PGwE773RW4XEFIT5s:bks4lp1)*

**Comment by web-padawan** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1#-:-L9iOS898W8UmImYoFzA:bg7igkv)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-vue/1)*

**Pull request merged**
